### PR TITLE
feat(SampleDistanceSlider/Style): Align center of button with slider, enable press-down feature

### PR DESCRIPTION
**Pull request by labdala**
- Create different selector for icon image so we can have a rule for the right margin.  This prevents vents the overlap between the slider and the icon.
 - Introduce `margin-top` rule in the style.css to align vertically the button/image icon and the slider.
- Change appearance of vertical slider
- Make buttons stay pressed down by using the selector `.checked` and change the color of `:focus` so it is different than the checked mode.

### CODE REVIEW

**Comment by labdala** [comment]
The last 3 commits come from a merge rebase from the blend-mode branch

**Review by PaulHax — CHANGES_REQUESTED** [review]
Very good!  One thing: when I click the Image icons, they get a gray background, like they are buttons.  Could be confusing, (more than they are already.)   I'm not sure, but I think this is probably due to a :focus css rule.  Can we make it so when the icons are clicked on, they do nothing.

**Comment by labdala** [comment]
@PaulHax Good catch. Indeed, it was a `:focus` issue and it has been fixed in the last version.

**Review by PaulHax — APPROVED** [review]
perfecto!

**Pull request merged**
