### PR TITLE
fix(ColorRangeInput): Support images with multiple color channels

### PR DESCRIPTION
**Pull request by labdala**
Fixes bug introduced in 2505e4634662f86f76377d3edb525441c76e9350.

### CODE REVIEW

**Review by PaulHax — COMMENTED** [review]
Better.  Couple other problems, we can address now or make an issue:
- The colormap is not applied to the transfer function editor on startup.   It should be red at the start.  Its just clear now.
- When I click component 2 tab, there is an error.

**Comment by labdala** [comment]
[a0b6b0b](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/80/commits/a0b6b0b1ef65b384ede16c19889dc2d37762f022) closes https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/issues/36

**Comment by labdala** [comment]
[a0b6b0b](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/80/commits/a0b6b0b1ef65b384ede16c19889dc2d37762f022) and [4d05464](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/80/commits/4d0546407e93c7de7a4f8a99c6d648f225ce8e55) close https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/issues/36

**Comment by labdala** [comment]
Closes #59

**Review by PaulHax — CHANGES_REQUESTED** [review]
Progress, but still have this problem:

With the `autronaut.zarr`,  when I click the "2" component tab, I get an error and UI dies.

**Comment by labdala** [comment]
> a0b6b0b

@PaulHax Interesting! Does this happen even after the last commits? On my end such behavior is fixed.

image

**Comment by PaulHax** [comment]
Ah, error does not happen when I have `use2d` true.  Here is a test case for a 3D image where the error happens:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/src/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Custom itk-viewer Boostrap UI Demo</title>
  </head>

  <body>
    <div
      class="content"
      style="
        position: absolute;
        width: 100vw;
        height: 100vh;
        top: 0;
        left: 0;
        overflow: hidden;
        background: black;
        margin: 0;
        padding: 0;
      "
    ></div>
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/itk-vtk-viewer@14/dist/itkVtkViewer.js"
    ></script>
    <script>
      const container = document.querySelector('.content')
      const image = new URL(
        'http://localhost:8082/test-data/ome-ngff-prototypes/single_image/v0.4/tczyx.ome.zarr',
        document.location.origin
      )
      const uiMachineOptions = {
        href: new URL(
          '/src/bootstrapUIMachineOptions.js',
          document.location.origin
        ).href
      }
      itkVtkViewer.createViewer(container, {
        image,
        rotate: false,
        config: { uiMachineOptions }
      })
    </script>
  </body>
</html>
```

**Comment by labdala** [comment]
Thanks @PaulHax ! Here you go!

**Review by PaulHax — APPROVED** [review]
Yeah, all better!

**Pull request merged**
